// <auto-generated />
namespace PRT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ivdonethisalot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ivdonethisalot));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171753463_iv done this alot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
